### ISSUE TITLE
安装失败，最小sdk多少？

### ISSUE THREAD

**Issue by rxzcums** [qqlittleice/FuckMiuiThemeManager#1]
![Screenshot_2022-03-09-08-29-41-371_com miui packageinstaller jpg](https://user-images.githubusercontent.com/11990604/157349299-2ba90d3c-efb0-424e-9c48-2916077600aa.png)

**Comment by rxzcums** [comment]
本机miui13,安卓12

**Comment by YuKongA** [comment]
我的问题，上传的版本损坏了

**Comment by rxzcums** [comment]
哈哈，好的，我等一下重新下载，现在下的还是坏的。

**Comment by YuKongA** [comment]
已经上传修复版本，去Xposed-Modules-Repo模块release自己下吧，lsp仓库那边刷新需要时间
