### ISSUE TITLE
收费字体用着就回退了

### ISSUE THREAD

**Issue by rxzcums** [qqlittleice/FuckMiuiThemeManager#2]
变回官方字体，log暂无

**Comment by YuKongA** [comment]
系统框架勾选并重启手机了么？系统框架得重新重启才能生效的。

**Comment by rxzcums** [comment]
> 系统框架勾选并重启手机了么？系统框架得重新重启才能生效的。

我应该是通过重启作用域起作用的，但是用着用着就回退，后来把手机重启了一次，目前没有回退，我再观察一下。

**Comment by YuKongA** [comment]
系统框架 重启作用域是没用的

**Comment by rxzcums** [comment]
> 系统框架 重启作用域是没用的

目前没有再出现，谢谢大哥
