### ISSUE TITLE
在模块列表中没有此模块

### ISSUE THREAD

**Issue by wangzhenxing4** [qqlittleice/FuckMiuiThemeManager#3]
设备:M2011K2C
android版本:12
MIUI版本:13.0.5
使用框架:zy版梦境
出现问题:模块列表中没有显示此模块
解决方法:无
出现几率:100%

**Comment by YuKongA** [comment]
如果梦境通过`xposedmodule`识别模块，那么解决方法就是往`AndroidManifest.xml`内添加

**Comment by YuKongA** [comment]
<meta-data
      android:name="xposedmodule"
      android:value="true" />

**Comment by YuKongA** [comment]
如果梦境通过 `xposedmodule` 识别模块，那么解决方法就是往 `AndroidManifest.xml` 内添加

`<meta-data
      android:name="xposedmodule"
      android:value="true" />`

即可解决
